name: AKIML-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1k
  - pandas=1.1.3
  - pillow=8.3.1
  - pip=21.1.3
  - py-xgboost=1.3.3
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.7
  - scipy=1.5.2
  - seaborn=0.11.0
  - setuptools=52.0.0
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.36.0
  - threadpoolctl=2.2.0
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - xgboost=1.3.3
  - pip:
    - altair==4.1.0
    - appdirs==1.4.4
    - argon2-cffi==20.1.0
    - astor==0.8.1
    - async-generator==1.10
    - attrs==20.3.0
    - backcall==0.2.0
    - base58==2.0.1
    - bleach==3.2.1
    - blinker==1.4
    - cachetools==4.2.0
    - cffi==1.14.4
    - chardet==3.0.4
    - click==7.1.2
    - decorator==4.4.2
    - defusedxml==0.6.0
    - distro==1.5.0
    - entrypoints==0.3
    - gitdb==4.0.5
    - gitpython==3.1.11
    - idna==2.10
    - ipykernel==5.4.0
    - ipython==7.19.0
    - ipywidgets==7.5.1
    - jedi==0.17.2
    - jinja2==2.11.2
    - jpype1==1.2.1
    - jsonschema==3.2.0
    - jupyterlab-pygments==0.1.2
    - markupsafe==1.1.1
    - mistune==0.8.4
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.0.8
    - nest-asyncio==1.4.3
    - notebook==6.1.5
    - packaging==20.7
    - pandocfilters==1.4.3
    - parso==0.7.1
    - pickle-mixin==1.0.2
    - pickleshare==0.7.5
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.8
    - protobuf==3.14.0
    - pyarrow==2.0.0
    - pycparser==2.20
    - pydeck==0.5.0
    - pygments==2.7.3
    - pyrsistent==0.17.3
    - pywin32==300
    - pywinpty==0.5.7
    - pyzmq==20.0.0
    - requests==2.25.0
    - scikit-learn==0.22.2.post1
    - send2trash==1.5.0
    - smmap==3.0.4
    - streamlit==0.72.0
    - tabula-py==2.2.0
    - terminado==0.9.1
    - testpath==0.4.4
    - toolz==0.11.1
    - tzlocal==2.1
    - urllib3==1.26.2
    - validators==0.18.1
    - watchdog==1.0.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
