name: AKIML-env
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - pandas=1.1.3
  - python=3.8
  - scikit-learn==0.22.2.post1
  - xgboost=1.3.3

